[package]
name = "padfolio"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
description = "Minimal Wayland clipboard manager"
repository = "https://github.com/verdiwm/padfolio"

[dependencies]
